server:
  port: 8006

spring:
  application:
    name: consul-provider-payment

#    consul注册中心地址
  cloud:
    consul:
      host: 192.168.1.108
      port: 8500
      discovery:
        service-name: ${spring.application.name}    # ${} 变量